In [2]:
import numpy as np
from random import randint

from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix
import itertools

In [3]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy

## Data Generation

In [4]:
train_samples = []
train_labels = []

In [5]:
for i in range(50):
    random_jr = randint(13, 64)
    train_samples.append(random_jr)
    train_labels.append(1)
    
    random_sr = randint(65, 100)
    train_samples.append(random_sr)
    train_labels.append(0)

for i in range(1000):
    random_jr = randint(13, 64)
    train_samples.append(random_jr)
    train_labels.append(0)
    
    random_sr = randint(65, 100)
    train_samples.append(random_sr)
    train_labels.append(1)

In [6]:
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

In [7]:
train_samples

array([35, 54, 37, ..., 77, 47, 34])

In [8]:
train_labels

array([0, 0, 0, ..., 1, 0, 0])

In [9]:
scaler = MinMaxScaler(feature_range=(0,1))
train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [10]:
train_samples

array([[0.25287356],
       [0.47126437],
       [0.27586207],
       ...,
       [0.73563218],
       [0.3908046 ],
       [0.24137931]])

## Building the model

In [11]:
model = Sequential([Dense(units=16, activation='relu', input_shape=(1,)),
                   Dense(units=32, activation='relu'),
                   Dense(units=2, activation='softmax')])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer=Adam(0.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.fit(x=train_samples, y=train_labels, batch_size=10, epochs=30, shuffle=True,  verbose=2,
         validation_split=0.1)

Train on 1890 samples, validate on 210 samples
Epoch 1/30
1890/1890 - 1s - loss: 0.6507 - accuracy: 0.5598 - val_loss: 0.6384 - val_accuracy: 0.5810
Epoch 2/30
1890/1890 - 0s - loss: 0.6208 - accuracy: 0.6407 - val_loss: 0.6075 - val_accuracy: 0.6762
Epoch 3/30
1890/1890 - 0s - loss: 0.5919 - accuracy: 0.7063 - val_loss: 0.5784 - val_accuracy: 0.7238
Epoch 4/30
1890/1890 - 0s - loss: 0.5635 - accuracy: 0.7413 - val_loss: 0.5491 - val_accuracy: 0.7619
Epoch 5/30
1890/1890 - 0s - loss: 0.5346 - accuracy: 0.7730 - val_loss: 0.5188 - val_accuracy: 0.8286
Epoch 6/30
1890/1890 - 0s - loss: 0.5052 - accuracy: 0.8106 - val_loss: 0.4881 - val_accuracy: 0.8476
Epoch 7/30
1890/1890 - 0s - loss: 0.4763 - accuracy: 0.8286 - val_loss: 0.4585 - val_accuracy: 0.8667
Epoch 8/30
1890/1890 - 0s - loss: 0.4484 - accuracy: 0.8529 - val_loss: 0.4300 - val_accuracy: 0.8857
Epoch 9/30
1890/1890 - 0s - loss: 0.4224 - accuracy: 0.8725 - val_loss: 0.4038 - val_accuracy: 0.8857
Epoch 10/30
1890/1890 - 0s - loss: 

## Generating test data

In [15]:
test_samples = []
test_labels = []

In [16]:
for i in range(10):
    random_jr = randint(13, 64)
    test_samples.append(random_jr)
    test_labels.append(1)
    
    random_sr = randint(65, 100)
    test_samples.append(random_sr)
    test_labels.append(0)

for i in range(200):
    random_jr = randint(13, 64)
    test_samples.append(random_jr)
    test_labels.append(0)
    
    random_sr = randint(65, 100)
    test_samples.append(random_sr)
    test_labels.append(1)

In [17]:
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)
test_labels, test_samples = shuffle(test_labels, test_samples)

In [18]:
test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

## Prediction

In [19]:
predictions = model.predict(x=test_samples, batch_size=10, verbose=0)

In [20]:
predictions

array([[0.8502278 , 0.14977229],
       [0.09428003, 0.90571994],
       [0.03235429, 0.96764576],
       [0.04479562, 0.9552044 ],
       [0.30100477, 0.69899523],
       [0.468503  , 0.53149694],
       [0.9556017 , 0.04439835],
       [0.02330204, 0.976698  ],
       [0.30100477, 0.69899523],
       [0.93452317, 0.0654768 ],
       [0.9094062 , 0.09059387],
       [0.21885784, 0.7811422 ],
       [0.9597664 , 0.0402336 ],
       [0.3644799 , 0.63552004],
       [0.9568825 , 0.0431175 ],
       [0.6099104 , 0.39008957],
       [0.5400118 , 0.45998818],
       [0.03807565, 0.96192443],
       [0.3644799 , 0.63552004],
       [0.9603668 , 0.03963325],
       [0.13641097, 0.863589  ],
       [0.8831839 , 0.11681604],
       [0.9538373 , 0.04616264],
       [0.9538373 , 0.04616264],
       [0.831054  , 0.168946  ],
       [0.9529304 , 0.04706962],
       [0.03510281, 0.9648972 ],
       [0.02530167, 0.97469836],
       [0.09428003, 0.90571994],
       [0.5400118 , 0.45998818],
       [0.

In [21]:
rounded_predictions = np.argmax(predictions, axis=-1)
rounded_predictions

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,

In [29]:
cm = confusion_matrix(y_true=test_labels, y_pred=rounded_predictions)
cm

array([[194,  16],
       [ 10, 200]], dtype=int64)

## Saving the model

In [34]:
import os.path
if os.path.isfile('C:/Users/Aryan/Deep Learning Projects/FreeCodeCamp - Keras (Deep Lizard).h5') is False:
    model.save('C:/Users/Aryan/Deep Learning Projects/FreeCodeCamp - Keras (Deep Lizard).h5')

In [35]:
from tensorflow.keras.models import load_model
new_model = load_model('C:/Users/Aryan/Deep Learning Projects/FreeCodeCamp - Keras (Deep Lizard).h5')

In [36]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                32        
_________________________________________________________________
dense_1 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [33]:
new_model.get_weights()

[array([[-0.5026033 , -0.49167803, -0.42634478, -0.5008931 ,  0.2270644 ,
         -0.26029688,  0.6626872 ,  0.17989561,  0.63479495, -0.08915073,
          0.5537687 ,  0.11403541, -0.02372611,  0.62219834,  0.27503207,
          0.30791938]], dtype=float32),
 array([ 0.        ,  0.        ,  0.        ,  0.        , -0.08067461,
         0.        , -0.14059384, -0.06714795,  0.044435  ,  0.        ,
        -0.12648532,  0.23093547,  0.        , -0.15597308, -0.09844253,
        -0.10802133], dtype=float32),
 array([[ 0.30480298, -0.16951285,  0.17436764,  0.12329775,  0.34916666,
         -0.00498793,  0.16284814, -0.17527348, -0.29618657,  0.29858783,
          0.24748275, -0.16803358, -0.21674968, -0.07359877,  0.3310732 ,
          0.11678538,  0.27694938,  0.19547692,  0.2474573 ,  0.28296444,
         -0.14566363, -0.07177398,  0.21437415,  0.00503698,  0.08403069,
         -0.09294644, -0.2025634 , -0.09870178,  0.29060706, -0.04529101,
         -0.15973444, -0.20178385],
 