In [1]:
import os
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 


Instructions for updating:
non-resource variables are not supported in the long term


# Constants

In [2]:
X_TRAIN_CSV = 'C:/Users/Aryan/Deep Learning Projects/MNIST/digit_xtrain.csv'
X_TEST_CSV = 'C:/Users/Aryan/Deep Learning Projects/MNIST/digit_xtest.csv'
Y_TRAIN_CSV = 'C:/Users/Aryan/Deep Learning Projects/MNIST/digit_ytrain.csv'
Y_TEST_CSV = 'C:/Users/Aryan/Deep Learning Projects/MNIST/digit_ytest.csv'

VALIDATION_SIZE = 10000

# 10000 + 50000 + 10000 = validation + training + testing

IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_HEIGHT * IMAGE_WIDTH * CHANNELS

In [3]:
y_train_all = np.loadtxt(Y_TRAIN_CSV, delimiter=',', dtype=int)

In [4]:
y_test = np.loadtxt(Y_TEST_CSV, delimiter=',', dtype=int)

In [5]:
x_train_all = np.loadtxt(X_TRAIN_CSV, delimiter=',', dtype=int)

In [6]:
x_test = np.loadtxt(X_TEST_CSV, delimiter=',', dtype=int)

# Explore 

In [7]:
x_train_all.shape

(60000, 784)

In [8]:
x_train_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [9]:
x_train_all[0].shape

(784,)

In [10]:
y_train_all.shape

(60000,)

In [11]:
y_train_all[0]

5

In [12]:
y_train_all.shape

(60000,)

In [13]:
x_test.shape

(10000, 784)

In [14]:
y_test.shape

(10000,)

In [15]:
y_train_all[:5]

array([5, 0, 4, 1, 9])

In [16]:
# X contains arrays in a row and Y contains corresponding values of that array
# X = array1, array2, array3...array70000
# Y = 5, 0, 4, 1, 9....8

# Data Preprocessing

In [17]:
# Rescale
# The neural network learns fast if the values of the inputs are between 0 and 1, therefore we scale our features

x_train_all, x_test = x_train_all/255.0, x_test/255.0

In [18]:
# One Hot Encoding to Y.
# So if the value present in Y is 5 then we will be converting it to : 0 0 0 0 1 0 0 0 0 0

values1 = y_train_all

In [56]:
np.eye(10) # Represents the numbers 0 to 9 in matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(10)[values1] # represents the numbers in y_train_all in matrix format


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [21]:
# So now we have array1, array2... in X
# And we have array1, array2,,, in Y too!

In [22]:
values2 = y_test
np.eye(10)[values2]

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
np.eye(10)[[3, 4]] # A simple example

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [24]:
y_train_all = np.eye(10)[values1]
y_test = np.eye(10)[values2]

# Create Validation Dataset from Training Dataset

In [25]:
x_valid = x_train_all[:VALIDATION_SIZE] # x_valid.shape = 10000
y_valid = y_train_all[:VALIDATION_SIZE] # y_valid.shape = 10000

In [26]:
x_train = x_train_all[VALIDATION_SIZE:]
y_train = y_train_all[VALIDATION_SIZE:]

# Setup Tensorflow Graph 

In [27]:
X = tf.placeholder(tf.float32, shape=[None, TOTAL_INPUTS])
Y = tf.placeholder(tf.float32, shape=[None, 10])

# Neural Network Architecture

In [28]:
 tf.__version__

'2.1.0'

# Neural Network Architecture
## Hyperparameters - Number of layers, number of nodes, number of epochs, etc.

In [29]:
nr_epochs = 5 
learning_rate = 0.0001

# Number of neurons in hidden layers

n_hidden1 = 512  # hidden layer-1 (relu)
n_hidden2 = 64   # hidden layer-2 (relu)
n_output = 10    # output layer  (softmax)

# Hidden Layer-1

## Generation of Weights

In [30]:
initial_w1 = tf.truncated_normal(shape=[TOTAL_INPUTS, n_hidden1], stddev=0.1, seed=42)  # Static variable
w1 = tf.Variable(initial_value=initial_w1)  # Changing variable

## Creating Bias

In [31]:
initial_b1 = tf.constant(0.0, shape=[n_hidden1])
b1 = tf.Variable(initial_value=initial_b1)

## Matrix Multiplication

In [32]:
layer1_in = tf.matmul(X, w1) + b1

## Activation Function

In [33]:
layer1_op = tf.nn.relu(layer1_in)

# Hidden Layer-2

In [34]:
initial_w2 = tf.truncated_normal(shape=[n_hidden1, n_hidden2], stddev=0.1, seed=42)
w2 = tf.Variable(initial_value=initial_w2)

In [35]:
initial_b2 = tf.constant(value=0.0, shape=[n_hidden2])
b2 = tf.Variable(initial_value=initial_b2)

In [36]:
layer2_in = tf.matmul(layer1_op, w2) + b2

In [37]:
layer2_op = tf.nn.relu(layer2_in)

# Output Layer

In [38]:
initial_w3 = tf.truncated_normal(shape=[n_hidden2, 10], stddev=0.1, seed=42)
w3 = tf.Variable(initial_value=initial_w3)

In [39]:
initial_b3 = tf.constant(value=0.0, shape=[10])
b3 = tf.Variable(initial_value=initial_b3)

In [40]:
layer3_in = tf.matmul(layer2_op, w3) + b3

In [41]:
output = tf.nn.softmax(layer3_in) # Output will be generated in terms of percentage values 

# Loss, Optimization and Metrics

In [42]:
# Loss Function

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))

In [43]:
# Optimizer

optimizer = tf.train.AdamOptimizer()
train_step = optimizer.minimize(loss)
# type(train_step)

In [44]:
# Accuracy 

correct_pred = tf.equal(tf.argmax(output, axis=1), tf.argmax(Y, axis=1)) # tf.argmax picks out the index having the highest probability
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Run Session

In [45]:
sess = tf.Session()

In [46]:
# Initialize all the variables

init = tf.global_variables_initializer()
sess.run(init)

In [47]:
b3.eval(sess)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

# Batching the Data

In [48]:
size_of_batch = 1000

In [49]:
num_examples = y_train.shape[0]  # data points

In [50]:
nr_iterations = int(num_examples/size_of_batch) # Number of batches

index_in_epoch = 0 # keeps a track when one batch ends and the other should start in one epoch

In [51]:
nr_iterations

50

In [52]:
def next_batch(batch_size, data, labels):
    
    global num_examples
    global index_in_epoch
    
    start =  index_in_epoch
    index_in_epoch += batch_size
    
    if index_in_epoch > num_examples:
        start = 0
        index_in_epoch = batch_size
    
    end = index_in_epoch
    
    return data[start:end], labels[start:end]

# Training Loop

In [53]:
for epoch in range(nr_epochs):
    
    for i in range(nr_iterations):
        
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_train, labels=y_train)
        
        feed_dictionary = {X:batch_x, Y:batch_y}
        sess.run(train_step, feed_dict=feed_dictionary)
        
        batch_accuracy = sess.run(fetches=[accuracy], feed_dict=feed_dictionary)
    
    print(f'Epoch - {epoch} \t| Training Accuracy = {batch_accuracy}')
print('Done Training!')

Epoch - 0 	| Training Accuracy = [0.859]
Epoch - 1 	| Training Accuracy = [0.867]
Epoch - 2 	| Training Accuracy = [0.871]
Epoch - 3 	| Training Accuracy = [0.875]
Epoch - 4 	| Training Accuracy = [0.877]
Done Training!
